version: "3"

networks:
  my-network:

services:

 nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
#     - ./data/certbot/conf:/etc/letsencrypt
#     - ./data/certbot/www:/var/www/certbot
    networks:
      - my-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  db:
    image: mariadb/server:10.4
    restart: always
    #command:
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=dbapi # name you want for the database
      - MYSQL_USER=dbuser # change to whatever username you want
      - MYSQL_PASSWORD=Usr@2020.. #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=Rt@2020.. #change to good root password
    ports:
      - "3306:3306"
    volumes:
      - "./db/files:/var/lib/mysql"
      - "./db/config:/etc/mysql/conf.d"
    networks:
      - my-network

  app:
    container_name: claseweb2.pikit.mx
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - my-network

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    networks:
#      - my-network
